USE `QuizApp`;
LOCK TABLES `USER` WRITE;
INSERT INTO `USER` VALUES ('27520001',
                                            '27520001',
                                            '27520001@gm.uit.edu.vn',
                                            'Lê Văn Luận',
                                            '60945',
                                            '1',
                                            '0');
INSERT INTO `USER` VALUES ('27520002',
                                            '27520002',
                                            '27520002@gm.uit.edu.vn',
                                            'Trần Công Danh',
                                            '10916',
                                            '1',
                                            '0');
INSERT INTO `USER` VALUES ('27520003',
                                            '27520003',
                                            '27520003@gm.uit.edu.vn',
                                            'Nguyễn Lê Quang Duy',
                                            '89189',
                                            '1',
                                            '0');
INSERT INTO `USER` VALUES ('27520004',
                                            '27520004',
                                            '27520004@gm.uit.edu.vn',
                                            'Nguyễn Quốc Thái',
                                            '97244',
                                            '1',
                                            '0');
INSERT INTO `USER` VALUES ('27520005',
                                            '27520005',
                                            '27520005@gm.uit.edu.vn',
                                            'Nguyễn Nhật Trương',
                                            '79746',
                                            '1',
                                            '0');
INSERT INTO `USER` VALUES ('27520006',
                                            '27520006',
                                            '27520006@gm.uit.edu.vn',
                                            'Nguyễn Xuân Duy Hiển',
                                            '34218',
                                            '1',
                                            '0');
INSERT INTO `USER` VALUES ('27520007',
                                            '27520007',
                                            '27520007@gm.uit.edu.vn',
                                            'Nguyễn Đắc Phi Hùng',
                                            '33292',
                                            '0',
                                            '0');
INSERT INTO `USER` VALUES ('27520008',
                                            '27520008',
                                            '27520008@gm.uit.edu.vn',
                                            'Thái Trung Hiếu',
                                            '22911',
                                            '0',
                                            '0');
INSERT INTO `USER` VALUES ('27520009',
                                            '27520009',
                                            '27520009@gm.uit.edu.vn',
                                            'Nguyễn Chí Bảo',
                                            '37655',
                                            '0',
                                            '0');
INSERT INTO `USER` VALUES ('27520010',
                                            '27520010',
                                            '27520010@gm.uit.edu.vn',
                                            'Nguyễn Duy Nhật',
                                            '21417',
                                            '0',
                                            '0');
INSERT INTO `USER` VALUES ('27520011',
                                            '27520011',
                                            '27520011@gm.uit.edu.vn',
                                            'Tăng Năng Chung',
                                            '47981',
                                            '0',
                                            '0');
INSERT INTO `USER` VALUES ('27520012',
                                            '27520012',
                                            '27520012@gm.uit.edu.vn',
                                            'Phan Thanh Hải',
                                            '83890',
                                            '0',
                                            '0');
INSERT INTO `USER` VALUES ('27520013',
                                            '27520013',
                                            '27520013@gm.uit.edu.vn',
                                            'Bùi Đào Gia Huy',
                                            '50034',
                                            '0',
                                            '0');
INSERT INTO `USER` VALUES ('27520014',
                                            '27520014',
                                            '27520014@gm.uit.edu.vn',
                                            'Nguyễn Đức Thịnh',
                                            '96742',
                                            '0',
                                            '0');
INSERT INTO `USER` VALUES ('27520015',
                                            '27520015',
                                            '27520015@gm.uit.edu.vn',
                                            'Đinh Hoàng Lộc',
                                            '84743',
                                            '0',
                                            '0');
INSERT INTO `USER` VALUES ('27520016',
                                            '27520016',
                                            '27520016@gm.uit.edu.vn',
                                            'Nguyễn Đăng Minh',
                                            '48810',
                                            '0',
                                            '0');
INSERT INTO `USER` VALUES ('27520017',
                                            '27520017',
                                            '27520017@gm.uit.edu.vn',
                                            'Đỗ Minh Trí',
                                            '78419',
                                            '0',
                                            '0');
INSERT INTO `USER` VALUES ('27520018',
                                            '27520018',
                                            '27520018@gm.uit.edu.vn',
                                            'Nguyễn Ngọc An',
                                            '27722',
                                            '0',
                                            '0');
INSERT INTO `USER` VALUES ('27520019',
                                            '27520019',
                                            '27520019@gm.uit.edu.vn',
                                            'Trịnh Bá Việt Anh',
                                            '75630',
                                            '0',
                                            '0');
INSERT INTO `USER` VALUES ('27520020',
                                            '27520020',
                                            '27520020@gm.uit.edu.vn',
                                            'Đỗ Vũ Gia Cần',
                                            '46066',
                                            '0',
                                            '0');
INSERT INTO `USER` VALUES ('27520021',
                                            '27520021',
                                            '27520021@gm.uit.edu.vn',
                                            'Trần Minh Đạt',
                                            '68514',
                                            '0',
                                            '0');
INSERT INTO `USER` VALUES ('27520022',
                                            '27520022',
                                            '27520022@gm.uit.edu.vn',
                                            'Hoàng Tiến Dũng',
                                            '19397',
                                            '0',
                                            '0');
INSERT INTO `USER` VALUES ('27520023',
                                            '27520023',
                                            '27520023@gm.uit.edu.vn',
                                            'Đỗ Nguyễn Hoàng Huy',
                                            '85502',
                                            '0',
                                            '0');
INSERT INTO `USER` VALUES ('27520024',
                                            '27520024',
                                            '27520024@gm.uit.edu.vn',
                                            'Nguyễn Đại Kỳ',
                                            '42226',
                                            '0',
                                            '0');
INSERT INTO `USER` VALUES ('27520025',
                                            '27520025',
                                            '27520025@gm.uit.edu.vn',
                                            'Nguyễn Lộc Linh',
                                            '60404',
                                            '0',
                                            '0');
INSERT INTO `USER` VALUES ('27520026',
                                            '27520026',
                                            '27520026@gm.uit.edu.vn',
                                            'Nguyễn Đức Phương Nguyên',
                                            '97194',
                                            '0',
                                            '0');
INSERT INTO `USER` VALUES ('27520027',
                                            '27520027',
                                            '27520027@gm.uit.edu.vn',
                                            'Nguyễn Ngọc Thái Nguyên',
                                            '37072',
                                            '0',
                                            '0');
INSERT INTO `USER` VALUES ('27520028',
                                            '27520028',
                                            '27520028@gm.uit.edu.vn',
                                            'Trần Duy Quang',
                                            '62814',
                                            '0',
                                            '0');
INSERT INTO `USER` VALUES ('27520029',
                                            '27520029',
                                            '27520029@gm.uit.edu.vn',
                                            'Lương Tường Quy',
                                            '67527',
                                            '0',
                                            '0');
INSERT INTO `USER` VALUES ('27520030',
                                            '27520030',
                                            '27520030@gm.uit.edu.vn',
                                            'Vũ Nguyễn Nhật Thanh',
                                            '78391',
                                            '0',
                                            '0');
INSERT INTO `USER` VALUES ('27520031',
                                            '27520031',
                                            '27520031@gm.uit.edu.vn',
                                            'Trương Thế Trương',
                                            '56684',
                                            '0',
                                            '0');
UNLOCK TABLES;
