USE `QuizApp`;
LOCK TABLES `SCORE` WRITE;
INSERT INTO `SCORE` VALUES ('120001',
                                            '73008',
                                            '27520015',
                                            '2',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120002',
                                            '73005',
                                            '27520013',
                                            '1',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120003',
                                            '73007',
                                            '27520018',
                                            '0',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120004',
                                            '73006',
                                            '27520020',
                                            '0',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120005',
                                            '73007',
                                            '27520014',
                                            '2',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120006',
                                            '73006',
                                            '27520019',
                                            '0',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120007',
                                            '73001',
                                            '27520021',
                                            '0',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120008',
                                            '73004',
                                            '27520018',
                                            '2',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120009',
                                            '73007',
                                            '27520021',
                                            '0',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120010',
                                            '73003',
                                            '27520019',
                                            '2',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120011',
                                            '73007',
                                            '27520021',
                                            '2',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120012',
                                            '73005',
                                            '27520020',
                                            '1',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120013',
                                            '73006',
                                            '27520028',
                                            '1',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120014',
                                            '73001',
                                            '27520024',
                                            '2',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120015',
                                            '73005',
                                            '27520024',
                                            '1',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120016',
                                            '73005',
                                            '27520024',
                                            '1',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120017',
                                            '73005',
                                            '27520026',
                                            '2',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120018',
                                            '73003',
                                            '27520030',
                                            '0',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120019',
                                            '73003',
                                            '27520010',
                                            '0',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120020',
                                            '73006',
                                            '27520010',
                                            '2',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120021',
                                            '73008',
                                            '27520010',
                                            '0',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120022',
                                            '73008',
                                            '27520013',
                                            '1',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120023',
                                            '73001',
                                            '27520010',
                                            '1',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120024',
                                            '73004',
                                            '27520008',
                                            '2',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120025',
                                            '73003',
                                            '27520016',
                                            '1',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120026',
                                            '73006',
                                            '27520016',
                                            '1',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120027',
                                            '73004',
                                            '27520016',
                                            '2',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120028',
                                            '73004',
                                            '27520013',
                                            '2',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120029',
                                            '73007',
                                            '27520019',
                                            '1',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120030',
                                            '73001',
                                            '27520021',
                                            '1',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120031',
                                            '73007',
                                            '27520020',
                                            '0',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120032',
                                            '73007',
                                            '27520021',
                                            '0',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120033',
                                            '73002',
                                            '27520019',
                                            '1',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120034',
                                            '73001',
                                            '27520018',
                                            '1',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120035',
                                            '73002',
                                            '27520025',
                                            '1',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120036',
                                            '73007',
                                            '27520026',
                                            '1',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120037',
                                            '73001',
                                            '27520029',
                                            '0',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120038',
                                            '73008',
                                            '27520022',
                                            '1',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120039',
                                            '73003',
                                            '27520023',
                                            '2',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120040',
                                            '73002',
                                            '27520028',
                                            '2',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120041',
                                            '73008',
                                            '27520008',
                                            '0',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120042',
                                            '73002',
                                            '27520011',
                                            '2',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120043',
                                            '73004',
                                            '27520008',
                                            '2',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120044',
                                            '73006',
                                            '27520010',
                                            '0',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120045',
                                            '73008',
                                            '27520031',
                                            '2',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120046',
                                            '73002',
                                            '27520031',
                                            '1',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120047',
                                            '73007',
                                            '27520013',
                                            '0',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120048',
                                            '73002',
                                            '27520009',
                                            '0',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120049',
                                            '73001',
                                            '27520011',
                                            '1',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120050',
                                            '73004',
                                            '27520018',
                                            '0',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120051',
                                            '73003',
                                            '27520013',
                                            '1',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120052',
                                            '73007',
                                            '27520021',
                                            '2',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120053',
                                            '73006',
                                            '27520019',
                                            '0',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120054',
                                            '73002',
                                            '27520014',
                                            '0',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120055',
                                            '73001',
                                            '27520021',
                                            '1',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120056',
                                            '73002',
                                            '27520017',
                                            '1',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120057',
                                            '73004',
                                            '27520023',
                                            '0',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120058',
                                            '73003',
                                            '27520019',
                                            '0',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120059',
                                            '73008',
                                            '27520027',
                                            '2',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120060',
                                            '73002',
                                            '27520029',
                                            '2',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120061',
                                            '73006',
                                            '27520030',
                                            '0',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120062',
                                            '73001',
                                            '27520027',
                                            '1',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120063',
                                            '73007',
                                            '27520031',
                                            '1',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120064',
                                            '73001',
                                            '27520009',
                                            '2',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120065',
                                            '73003',
                                            '27520025',
                                            '2',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120066',
                                            '73003',
                                            '27520011',
                                            '0',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120067',
                                            '73002',
                                            '27520012',
                                            '1',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120068',
                                            '73001',
                                            '27520030',
                                            '2',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120069',
                                            '73004',
                                            '27520030',
                                            '2',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120070',
                                            '73007',
                                            '27520010',
                                            '1',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120071',
                                            '73004',
                                            '27520031',
                                            '2',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120072',
                                            '73004',
                                            '27520012',
                                            '1',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120073',
                                            '73004',
                                            '27520011',
                                            '2',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120074',
                                            '73004',
                                            '27520010',
                                            '2',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120075',
                                            '73004',
                                            '27520012',
                                            '1',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120076',
                                            '73006',
                                            '27520019',
                                            '2',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120077',
                                            '73007',
                                            '27520020',
                                            '2',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120078',
                                            '73008',
                                            '27520018',
                                            '0',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120079',
                                            '73006',
                                            '27520016',
                                            '2',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120080',
                                            '73006',
                                            '27520025',
                                            '2',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120081',
                                            '73001',
                                            '27520022',
                                            '0',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120082',
                                            '73005',
                                            '27520025',
                                            '0',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120083',
                                            '73008',
                                            '27520028',
                                            '0',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120084',
                                            '73006',
                                            '27520028',
                                            '2',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120085',
                                            '73003',
                                            '27520021',
                                            '0',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120086',
                                            '73006',
                                            '27520022',
                                            '2',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120087',
                                            '73006',
                                            '27520030',
                                            '1',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120088',
                                            '73001',
                                            '27520025',
                                            '2',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120089',
                                            '73003',
                                            '27520028',
                                            '2',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120090',
                                            '73004',
                                            '27520011',
                                            '0',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120091',
                                            '73004',
                                            '27520027',
                                            '1',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120092',
                                            '73006',
                                            '27520011',
                                            '0',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120093',
                                            '73007',
                                            '27520011',
                                            '2',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120094',
                                            '73006',
                                            '27520031',
                                            '2',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120095',
                                            '73001',
                                            '27520011',
                                            '0',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120096',
                                            '73005',
                                            '27520014',
                                            '1',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120097',
                                            '73003',
                                            '27520009',
                                            '2',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120098',
                                            '73003',
                                            '27520013',
                                            '0',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120099',
                                            '73005',
                                            '27520015',
                                            '1',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120100',
                                            '73006',
                                            '27520019',
                                            '1',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120101',
                                            '73006',
                                            '27520013',
                                            '2',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120102',
                                            '73007',
                                            '27520019',
                                            '2',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120103',
                                            '73002',
                                            '27520022',
                                            '1',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120104',
                                            '73006',
                                            '27520023',
                                            '1',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120105',
                                            '73003',
                                            '27520018',
                                            '2',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120106',
                                            '73003',
                                            '27520025',
                                            '1',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120107',
                                            '73002',
                                            '27520021',
                                            '1',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120108',
                                            '73003',
                                            '27520025',
                                            '1',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120109',
                                            '73001',
                                            '27520024',
                                            '1',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120110',
                                            '73008',
                                            '27520028',
                                            '1',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120111',
                                            '73001',
                                            '27520023',
                                            '1',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120112',
                                            '73007',
                                            '27520024',
                                            '2',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120113',
                                            '73008',
                                            '27520030',
                                            '0',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120114',
                                            '73003',
                                            '27520027',
                                            '0',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120115',
                                            '73007',
                                            '27520011',
                                            '1',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120116',
                                            '73005',
                                            '27520028',
                                            '2',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120117',
                                            '73001',
                                            '27520009',
                                            '0',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120118',
                                            '73008',
                                            '27520013',
                                            '0',
                                            '1',
                                            '0');
INSERT INTO `SCORE` VALUES ('120119',
                                            '73006',
                                            '27520016',
                                            '0',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120120',
                                            '73004',
                                            '27520015',
                                            '2',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120121',
                                            '73005',
                                            '27520015',
                                            '1',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120122',
                                            '73007',
                                            '27520013',
                                            '2',
                                            '0',
                                            '0');
INSERT INTO `SCORE` VALUES ('120123',
                                            '73004',
                                            '27520012',
                                            '2',
                                            '2',
                                            '0');
INSERT INTO `SCORE` VALUES ('120124',
                                            '73008',
                                            '27520015',
                                            '0',
                                            '0',
                                            '0');
UNLOCK TABLES;
