USE `QuizApp`;
LOCK TABLES `QUIZ_QUESTION` WRITE;
INSERT INTO `QUIZ_QUESTION` VALUES ('1',
                                            '73001',
                                            'Bạn có đi học ngày hôm nay không?',
                                            'Có',
                                            'Không',
                                            '',
                                            '',
                                            '0',
                                            '0');
INSERT INTO `QUIZ_QUESTION` VALUES ('2',
                                            '73001',
                                            'Viết câu lệnh in ra màn hình "Hello world!" bằng Python.',
                                            'sys.out("Hello World")',
                                            'print("Hello World")',
                                            'cout << "Hello World!";',
                                            'cin >> "Hello world!";',
                                            '1',
                                            '0');
INSERT INTO `QUIZ_QUESTION` VALUES ('3',
                                            '73002',
                                            'Bạn có đi học ngày hôm nay không?',
                                            'Có',
                                            'Không',
                                            '',
                                            '',
                                            '0',
                                            '0');
INSERT INTO `QUIZ_QUESTION` VALUES ('4',
                                            '73002',
                                            'Viết câu lệnh in ra màn hình "Hello world!" bằng Python.',
                                            'sys.out("Hello World")',
                                            'print("Hello World")',
                                            'cout << "Hello World!";',
                                            'cin >> "Hello world!";',
                                            '1',
                                            '0');
INSERT INTO `QUIZ_QUESTION` VALUES ('5',
                                            '73003',
                                            'Bạn có đi học ngày hôm nay không?',
                                            'Có',
                                            'Không',
                                            '',
                                            '',
                                            '0',
                                            '0');
INSERT INTO `QUIZ_QUESTION` VALUES ('6',
                                            '73003',
                                            'Câu lệnh xuất tổng của 2 biến a, b trong Python là:',
                                            'cout << a+b;',
                                            'print(a+b)',
                                            'cin >> a+b;',
                                            'sys.console.print(a+b);',
                                            '1',
                                            '0');
INSERT INTO `QUIZ_QUESTION` VALUES ('7',
                                            '73004',
                                            'Bạn có đi học ngày hôm nay không?',
                                            'Có',
                                            'Không',
                                            '',
                                            '',
                                            '0',
                                            '0');
INSERT INTO `QUIZ_QUESTION` VALUES ('8',
                                            '73004',
                                            'Câu lệnh cho vòng lặp for chạy n lần trong Python là:',
                                            'for i in range(n):',
                                            'for i in range(1,n):',
                                            'for _ in range(1,n)',
                                            'for hehe in list(n):',
                                            '0',
                                            '0');
INSERT INTO `QUIZ_QUESTION` VALUES ('9',
                                            '73005',
                                            'Bạn có đi học ngày hôm nay không?',
                                            'Có',
                                            'Không',
                                            '',
                                            '',
                                            '0',
                                            '0');
INSERT INTO `QUIZ_QUESTION` VALUES ('10',
                                            '73005',
                                            'Câu lệnh chọn tất cả các dòng trong bảng user của mysql là:',
                                            'SELECT ALL FROM USER',
                                            'SELECT ALL ABOUT USER',
                                            'SELECT * FROM USER',
                                            'SELECT X FROM USER',
                                            '2',
                                            '0');
INSERT INTO `QUIZ_QUESTION` VALUES ('11',
                                            '73006',
                                            'Bạn có đi học ngày hôm nay không?',
                                            'Có',
                                            'Không',
                                            '',
                                            '',
                                            '0',
                                            '0');
INSERT INTO `QUIZ_QUESTION` VALUES ('12',
                                            '73006',
                                            'Câu lệnh chọn tất cả các dòng trong bảng user của mysql là:',
                                            'SELECT ALL FROM USER',
                                            'SELECT ALL ABOUT USER',
                                            'SELECT * FROM USER',
                                            'SELECT X FROM USER',
                                            '2',
                                            '0');
INSERT INTO `QUIZ_QUESTION` VALUES ('13',
                                            '73007',
                                            'Bạn có đi học ngày hôm nay không?',
                                            'Có',
                                            'Không',
                                            '',
                                            '',
                                            '0',
                                            '0');
INSERT INTO `QUIZ_QUESTION` VALUES ('14',
                                            '73007',
                                            'Ngày hôm nay của bạn thế nào?',
                                            'Bình thường',
                                            'Bí mật',
                                            'Tốt',
                                            'Tệ',
                                            '1',
                                            '0');
INSERT INTO `QUIZ_QUESTION` VALUES ('15',
                                            '73008',
                                            'Bạn có đi học ngày hôm nay không?',
                                            'Có',
                                            'Không',
                                            '',
                                            '',
                                            '0',
                                            '0');
INSERT INTO `QUIZ_QUESTION` VALUES ('16',
                                            '73008',
                                            'Bạn đánh giá môn học này như thế nào?',
                                            'Quá tệ',
                                            'Tệ',
                                            'Cũng được',
                                            'Tốt',
                                            '3',
                                            '0');
UNLOCK TABLES;
